---
redis_version: "7.0.15"

redis_port: 6379
redis_cluster_bus_port: 16379
redis_cluster_node_timeout: 15000

redis_install_dir: /usr/local/redis-{{ redis_version }}
redis_bin_dir: "{{ redis_install_dir }}/bin"
redis_symlink_dir: /usr/local/bin

redis_config_dir: /etc/redis
redis_config_file: "{{ redis_config_dir }}/redis.conf"
redis_data_dir: /var/lib/redis
redis_log_dir: /var/log/redis
redis_pid_file: /var/run/redis/redis-server.pid

redis_bind_address: "0.0.0.0"
redis_maxmemory: "256mb"

redis_download_url: "http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz"
redis_src_dir: "/usr/local/src/redis-{{ redis_version }}"