---
- name: Verify Redis Cluster
  hosts: redis_cluster
  gather_facts: false

  tasks:

    - name: Get Redis version
      command: /usr/local/bin/redis-cli -p 6379 info server
      register: version_info
      changed_when: false

    - name: Get replication info
      command: /usr/local/bin/redis-cli -p 6379 info replication
      register: replication_info
      changed_when: false

    - name: Get cluster info
      command: /usr/local/bin/redis-cli -p 6379 cluster info
      register: cluster_info
      changed_when: false